### ISSUE TITLE
undefined method `connect' for Redis:Class #19

### ISSUE THREAD

**Issue by eldadfux** [resque/resque-web#136]
This seems to happen because of breaking changes introduces with redis 4.0.

GEM dependency should be set to redis 3.5.* or method should be changes to work with redis 4.0

A working workaround I used is to setup redis 3.5 before installing resque-web.

`gem install redis --version 3.3.5 && gem install resque-web`

**Comment by jeremy** [comment]
https://github.com/resque/resque/pull/1593 👍
